### ISSUE TITLE
Usage information

### ISSUE THREAD

**Issue by DanielRuf** [renovatebot/docker-yarn#36]
I miss some readme with instructions to use this.

**Comment by ViceIce** [comment]
This docker image is only used by renovatebot and not standalone.

**Comment by rarkins** [comment]
We can add a readme though. Also needs a v2 added

**Comment by DanielRuf** [comment]
> This docker image is only used by renovatebot and not standalone.

I've seen that but I would build on that and reuse it as it is a bit smaller and easier than other images and their Dockerfiles.

> We can add a readme though. Also needs a v2 added

That would be great.
