### ISSUE TITLE
Automated builds

### ISSUE THREAD

**Issue by rarkins** [renovatebot/docker-yarn#7]
We want to build a separate Docker image for every Yarn release that users might be still using, and ideally make it as automated as possible.

To do this, we need to know both a minimum as well as maximum version to build.

We should also have the ability to completely rebuild every image in future, e.g. if we find that we need to apply a security update to the underlying Node.js base image.

If the base Docker image changes, we want to rebuild every image - or perhaps just the ones we consider "supported" (above the minimum version).

If the maximum version changes, we want to just build that one and not rebuild all the others.

**Comment by rarkins** [comment]
For each image:
- Pull it
- Build it
- If the build has changed, push it

So how to determine if the build changed? `docker image inspect --format='{{.ID}}' renovate/yarn:1.13.0`

**Comment by viceice** [comment]
we can use buildx like in renovate. it will rebuild always the same id, so you can push, but it will not change anything

**Comment by viceice** [comment]
We should migrate to github actions too here and for all other renovate images

**Comment by rarkins** [comment]
We do actually have automated builds but it’s based on the image tag only. Ie of yarn:1.22.0 already exists then it will never be rebuilt without human intervention, even if a bare changes. Buildx caching would solve that. Let’s try to measure first whether actions caching is faster than hub caching and then role a common solution out to all images

**Comment by viceice** [comment]
I think this works now.
